version: '3.8'

services:
    dev:
        container_name: nestjs_api_clima_tempo
        image: nestjs-api:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
        networks:
            - default
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    default:
        driver: bridge
